name: Publish update

on:
  push:
    branches: ['*']

jobs:
  tsc-lint:
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: tsc
        run: yarn tsc
      - name: lint
        run: yarn lint
  update:
    needs: tsc-lint
    type: update
